### ISSUE TITLE
Log4Net.Async dll not copied to output if library is unreferenced in code

### ISSUE THREAD

**Issue by rowandh** [cjbhaines/Log4Net.Async#1]
If the Log4Net.Async library is only referenced in non-code (eg. a log4net log.config file), then the VS build process will not automatically copy the Log4Net.Async dll to the build folder for projects that reference other projects using Log4Net.Async. This occurs even if Copy Local is set to "True".

To get around this I created a dummy class whose sole purpose is to extend the RingBuffer class, without actually doing anything or being used anywhere at all.

A note about this in the documentation would be very helpful for those who are solely looking to wrap their existing appenders in their log config file.

**Comment by cjbhaines** [comment]
Richard, in that case I will close this off then, thanks for checking. Even if it didn't there's not really much we can do to address it, it's almost an issue with MSBuild outputs.

**Comment by PoorDesigner** [comment]
Is there any code snippet/implementation on how to extend the RingBuffer class ?

**Comment by cjbhaines** [comment]
@PoorDesigner why would you want to extend it?

**Comment by PoorDesigner** [comment]
I am using a shared library and Log4net async  is only referred in config.  I am trying to use the workaround that you mentioned

"To get around this I created a dummy class whose sole purpose is to extend the RingBuffer class, without actually doing anything or being used anywhere at all."

**Comment by PoorDesigner** [comment]
I think I understood  what  we need to do.  We need to refer the async library in the code somewhere so that the dll will be copied to output.  I'll try that. 
Thanks

**Comment by cjbhaines** [comment]
@PoorDesigner so I did, my apologies it's been a while since I looked at this stuff. There was an open issue this afternoon with a suggestion to add an Attribute that could be applied in an AssemblyInfo to force the compiler to reference the library. I pushed a new NuGet package this afternoon and I've just updated the Readme in the Notes section with how to use this.

**Comment by PoorDesigner** [comment]
when i try to use this in AssemblyInfo it gives me "Assembly generation failed as log4net.async doesn't have a strong name"

**Comment by cjbhaines** [comment]
That's a different issue. I do not sign the Log4Net.Async assemblies so if you are signing your assemblies you won't be able to reference it without a work around.

http://stackoverflow.com/questions/331520/how-to-fix-referenced-assembly-does-not-have-a-strong-name-error

**Comment by PoorDesigner** [comment]
Yeah i looked through those. But i would like to know whether there is any chance of giving us signed one ? :)
