### ISSUE TITLE
LogicalThreadContext properties not logged

### ISSUE THREAD

**Issue by codecutout** [cjbhaines/Log4Net.Async#10]
When using the AsyncRollingFileAppender and adding properties view LogicalThreadContext the properties are not logged.

Seems to be resolving the properties lazily, so it is resolving properties in the context of the AppendTask rather than in the context  the message was added to the log.

**Comment by cjbhaines** [comment]
I'm reluctant to do any more work on the async appenders. I'm tempted to even obsolete them or possibly remove them in a major version bump release. The AsyncForwarder is a much better solution and you can also wrap multiple appenders in one forwarder to reduce the number of background threads you have running. The bug you mention is not present in the AsyncForwarder.
