### ISSUE TITLE
Suggestion for "CopyLocal" issue

### ISSUE THREAD

**Issue by th3ragex** [cjbhaines/Log4Net.Async#17]
This problem also exists for WPF "only" referenced libraries.

A simple solution for this would be to add a simple attribue to the library and refernence it, for exampel in the AssemblyInfo.cs

The attribute:

using System;
namespace MyNamespace
{
  [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = false)]
  public class ReferencedLibraryAttribute : Attribute
  {
  }
}

in AssemblyInfo of the using project:
[assembly: ReferencedLibrary]

**Comment by cjbhaines** [comment]
I like this because you can hide it out the way in the AssemblyInfo. Fancy sending a PR?

**Comment by cjbhaines** [comment]
Fixed by b235183170904ba1070999ecf7e829d9754fb51a . Packages pushed to NuGet as 2.0.1.0
