### ISSUE TITLE
Simple demo application required

### ISSUE THREAD

**Issue by kanadmehta** [cjbhaines/Log4Net.Async#31]
Can anyone please provide a simple form and log event asynchronously to database.
Or sample code can do as well.

Thank you in advance.

**Comment by cjbhaines** [comment]
There are sample configs for the AdoNetAppender on the log4net website and you then just need to wrap it in the async forwarder or appender as shown in the readme of this project.

https://logging.apache.org/log4net/release/config-examples.html
