### ISSUE TITLE
Throttling support?

### ISSUE THREAD

**Issue by Shazwazza** [cjbhaines/Log4Net.Async#35]
I was wondering if it would be possible or how easy it would be to implement a throttling config switch in case you want to stop the logging in case something is flooding them (especially useful when wrapping the ADO appender)?

I saw some code on a forked project here https://github.com/salyh/log4net-asyncforwardingappender/blob/master/AsynchronousBufferingForwardingAppender/AsynchronousBufferingForwardingAppender.cs which says it does this so wanted to see if that's something that could be integrated to this lib?

Thanks!

**Comment by rcollette** [comment]
While not a bad idea, I would keep the concerns separated . I would implement it as a separate forwarding appender.

**Comment by Shazwazza** [comment]
OK thanks for the feedback, i'll see what i can come up with
