### ISSUE TITLE
AsyncForwardingAppender causing WPF application to hang on application exit

### ISSUE THREAD

**Issue by renns** [cjbhaines/Log4Net.Async#7]
I added the AsyncForwardingAppender to a WPF application, and when I exit the application, it stays running. I tracked the cause to the AsyncForwardingAppender. I tried ParallelForwardingAppender and that had no problem.

My setup:
In the App.xaml.cs constructor, I have XmlConfigurator.Configure();.
In my App.config, my root logger has a reference to the AsyncForwardingAppender and the AsyncForwardingAppender has references to my other appenders.

I was able to get it to exit if I put "log4net.LogManager.Shutdown();" in the Application_Exit method. However, I don't think that should be necessary.

I also have the same logging being used in windows services and they have no problem stopping.

**Comment by cjbhaines** [comment]
If you are using log4net it is good practice to call LogManager.Shutdown on your application exit. In this scenario it will clean up all your logging threads. Because log4net is an extensible library you have no control over what resources it is managing so you should always stop it gracefully.
